// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proxy/masque/config.proto

package masque

import (
	net "github.com/exclavenetwork/exclave-core/v5/common/net"
	_ "github.com/exclavenetwork/exclave-core/v5/common/protoext"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientConfig_DomainStrategy int32

const (
	ClientConfig_USE_IP     ClientConfig_DomainStrategy = 0
	ClientConfig_USE_IP4    ClientConfig_DomainStrategy = 1
	ClientConfig_USE_IP6    ClientConfig_DomainStrategy = 2
	ClientConfig_PREFER_IP4 ClientConfig_DomainStrategy = 3
	ClientConfig_PREFER_IP6 ClientConfig_DomainStrategy = 4
)

// Enum value maps for ClientConfig_DomainStrategy.
var (
	ClientConfig_DomainStrategy_name = map[int32]string{
		0: "USE_IP",
		1: "USE_IP4",
		2: "USE_IP6",
		3: "PREFER_IP4",
		4: "PREFER_IP6",
	}
	ClientConfig_DomainStrategy_value = map[string]int32{
		"USE_IP":     0,
		"USE_IP4":    1,
		"USE_IP6":    2,
		"PREFER_IP4": 3,
		"PREFER_IP6": 4,
	}
)

func (x ClientConfig_DomainStrategy) Enum() *ClientConfig_DomainStrategy {
	p := new(ClientConfig_DomainStrategy)
	*p = x
	return p
}

func (x ClientConfig_DomainStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientConfig_DomainStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proxy_masque_config_proto_enumTypes[0].Descriptor()
}

func (ClientConfig_DomainStrategy) Type() protoreflect.EnumType {
	return &file_proxy_masque_config_proto_enumTypes[0]
}

func (x ClientConfig_DomainStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientConfig_DomainStrategy.Descriptor instead.
func (ClientConfig_DomainStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proxy_masque_config_proto_rawDescGZIP(), []int{0, 0}
}

type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Endpoint of the MASQUE proxy, used in QUIC (HTTP/3) mode.
	Address *net.IPOrDomain `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Port    uint32          `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Endpoint used in HTTP/2 mode instead of `address`. Optional.
	Http2Address *net.IPOrDomain `protobuf:"bytes,3,opt,name=http2_address,json=http2Address,proto3" json:"http2_address,omitempty"`
	// Base64 encoded DER of the enrolled ECDSA P-256 private key.
	PrivateKey string `protobuf:"bytes,4,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	// PEM encoded PKIX public key of the endpoint, pinned during the handshake.
	EndpointPublicKey string `protobuf:"bytes,5,opt,name=endpoint_public_key,json=endpointPublicKey,proto3" json:"endpoint_public_key,omitempty"`
	// Addresses assigned to this device inside the tunnel.
	LocalAddress []string `protobuf:"bytes,6,rep,name=local_address,json=localAddress,proto3" json:"local_address,omitempty"`
	ServerName   string   `protobuf:"bytes,7,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Mtu          int32    `protobuf:"varint,8,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Connect over TCP+TLS/HTTP2 instead of QUIC/HTTP3.
	UseHttp2 bool `protobuf:"varint,9,opt,name=use_http2,json=useHttp2,proto3" json:"use_http2,omitempty"`
	// Skip endpoint public key pinning.
	AllowInsecure bool `protobuf:"varint,10,opt,name=allow_insecure,json=allowInsecure,proto3" json:"allow_insecure,omitempty"`
	// QUIC keep alive period in seconds. 0 selects the default.
	KeepalivePeriod uint32 `protobuf:"varint,11,opt,name=keepalive_period,json=keepalivePeriod,proto3" json:"keepalive_period,omitempty"`
	// Fixed QUIC initial packet size. 0 keeps path MTU discovery enabled.
	InitialPacketSize uint32                      `protobuf:"varint,12,opt,name=initial_packet_size,json=initialPacketSize,proto3" json:"initial_packet_size,omitempty"`
	DomainStrategy    ClientConfig_DomainStrategy `protobuf:"varint,13,opt,name=domain_strategy,json=domainStrategy,proto3,enum=exclave.core.proxy.masque.ClientConfig_DomainStrategy" json:"domain_strategy,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_masque_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_masque_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_masque_config_proto_rawDescGZIP(), []int{0}
}

func (x *ClientConfig) GetAddress() *net.IPOrDomain {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ClientConfig) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ClientConfig) GetHttp2Address() *net.IPOrDomain {
	if x != nil {
		return x.Http2Address
	}
	return nil
}

func (x *ClientConfig) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *ClientConfig) GetEndpointPublicKey() string {
	if x != nil {
		return x.EndpointPublicKey
	}
	return ""
}

func (x *ClientConfig) GetLocalAddress() []string {
	if x != nil {
		return x.LocalAddress
	}
	return nil
}

func (x *ClientConfig) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ClientConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ClientConfig) GetUseHttp2() bool {
	if x != nil {
		return x.UseHttp2
	}
	return false
}

func (x *ClientConfig) GetAllowInsecure() bool {
	if x != nil {
		return x.AllowInsecure
	}
	return false
}

func (x *ClientConfig) GetKeepalivePeriod() uint32 {
	if x != nil {
		return x.KeepalivePeriod
	}
	return 0
}

func (x *ClientConfig) GetInitialPacketSize() uint32 {
	if x != nil {
		return x.InitialPacketSize
	}
	return 0
}

func (x *ClientConfig) GetDomainStrategy() ClientConfig_DomainStrategy {
	if x != nil {
		return x.DomainStrategy
	}
	return ClientConfig_USE_IP
}

var File_proxy_masque_config_proto protoreflect.FileDescriptor

const file_proxy_masque_config_proto_rawDesc = "" +
	"\n" +
	"\x19proxy/masque/config.proto\x12\x19exclave.core.proxy.masque\x1a common/protoext/extensions.proto\x1a\x18common/net/address.proto\"\xc4\x05\n" +
	"\fClientConfig\x12=\n" +
	"\aaddress\x18\x01 \x01(\v2#.exclave.core.common.net.IPOrDomainR\aaddress\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12H\n" +
	"\rhttp2_address\x18\x03 \x01(\v2#.exclave.core.common.net.IPOrDomainR\fhttp2Address\x12\x1f\n" +
	"\vprivate_key\x18\x04 \x01(\tR\n" +
	"privateKey\x12.\n" +
	"\x13endpoint_public_key\x18\x05 \x01(\tR\x11endpointPublicKey\x12#\n" +
	"\rlocal_address\x18\x06 \x03(\tR\flocalAddress\x12\x1f\n" +
	"\vserver_name\x18\a \x01(\tR\n" +
	"serverName\x12\x10\n" +
	"\x03mtu\x18\b \x01(\x05R\x03mtu\x12\x1b\n" +
	"\tuse_http2\x18\t \x01(\bR\buseHttp2\x12%\n" +
	"\x0eallow_insecure\x18\n" +
	" \x01(\bR\rallowInsecure\x12)\n" +
	"\x10keepalive_period\x18\v \x01(\rR\x0fkeepalivePeriod\x12.\n" +
	"\x13initial_packet_size\x18\f \x01(\rR\x11initialPacketSize\x12_\n" +
	"\x0fdomain_strategy\x18\r \x01(\x0e26.exclave.core.proxy.masque.ClientConfig.DomainStrategyR\x0edomainStrategy\"V\n" +
	"\x0eDomainStrategy\x12\n" +
	"\n" +
	"\x06USE_IP\x10\x00\x12\v\n" +
	"\aUSE_IP4\x10\x01\x12\v\n" +
	"\aUSE_IP6\x10\x02\x12\x0e\n" +
	"\n" +
	"PREFER_IP4\x10\x03\x12\x0e\n" +
	"\n" +
	"PREFER_IP6\x10\x04:\x16\x82\xb5\x18\x12\n" +
	"\boutbound\x12\x06masqueB\x8b\x01\n" +
	"3com.github.exclavenetwork.exclave.core.proxy.masqueP\x01Z6github.com/exclavenetwork/exclave-core/v5/proxy/masque\xaa\x02\x19Exclave.Core.Proxy.Masqueb\x06proto3"

var (
	file_proxy_masque_config_proto_rawDescOnce sync.Once
	file_proxy_masque_config_proto_rawDescData []byte
)

func file_proxy_masque_config_proto_rawDescGZIP() []byte {
	file_proxy_masque_config_proto_rawDescOnce.Do(func() {
		file_proxy_masque_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_masque_config_proto_rawDesc), len(file_proxy_masque_config_proto_rawDesc)))
	})
	return file_proxy_masque_config_proto_rawDescData
}

var file_proxy_masque_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proxy_masque_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proxy_masque_config_proto_goTypes = []any{
	(ClientConfig_DomainStrategy)(0), // 0: exclave.core.proxy.masque.ClientConfig.DomainStrategy
	(*ClientConfig)(nil),             // 1: exclave.core.proxy.masque.ClientConfig
	(*net.IPOrDomain)(nil),           // 2: exclave.core.common.net.IPOrDomain
}
var file_proxy_masque_config_proto_depIdxs = []int32{
	2, // 0: exclave.core.proxy.masque.ClientConfig.address:type_name -> exclave.core.common.net.IPOrDomain
	2, // 1: exclave.core.proxy.masque.ClientConfig.http2_address:type_name -> exclave.core.common.net.IPOrDomain
	0, // 2: exclave.core.proxy.masque.ClientConfig.domain_strategy:type_name -> exclave.core.proxy.masque.ClientConfig.DomainStrategy
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proxy_masque_config_proto_init() }
func file_proxy_masque_config_proto_init() {
	if File_proxy_masque_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_masque_config_proto_rawDesc), len(file_proxy_masque_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_masque_config_proto_goTypes,
		DependencyIndexes: file_proxy_masque_config_proto_depIdxs,
		EnumInfos:         file_proxy_masque_config_proto_enumTypes,
		MessageInfos:      file_proxy_masque_config_proto_msgTypes,
	}.Build()
	File_proxy_masque_config_proto = out.File
	file_proxy_masque_config_proto_goTypes = nil
	file_proxy_masque_config_proto_depIdxs = nil
}
